/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPoSQLVerifier, IPoSQLVerifierInterface } from "../../../voting/MintController.sol/IPoSQLVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "query",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "verifyQuery",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IPoSQLVerifier__factory {
    static readonly abi = _abi;
    static createInterface(): IPoSQLVerifierInterface {
      return new Interface(_abi) as IPoSQLVerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPoSQLVerifier {
      return new Contract(address, _abi, runner) as unknown as IPoSQLVerifier;
    }
  }
  