/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FeedbackInterface extends Interface {
    getFunction(nameOrSignature: "groupId" | "joinGroup" | "semaphore" | "sendFeedback"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'groupId', values?: undefined): string;
encodeFunctionData(functionFragment: 'joinGroup', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'semaphore', values?: undefined): string;
encodeFunctionData(functionFragment: 'sendFeedback', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'groupId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinGroup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'semaphore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendFeedback', data: BytesLike): Result;
  }

  

  export interface Feedback extends BaseContract {
    
    connect(runner?: ContractRunner | null): Feedback;
    waitForDeployment(): Promise<this>;

    interface: FeedbackInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    groupId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    joinGroup: TypedContractMethod<
      [identityCommitment: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    semaphore: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    sendFeedback: TypedContractMethod<
      [merkleTreeDepth: BigNumberish, merkleTreeRoot: BigNumberish, nullifier: BigNumberish, feedback: BigNumberish, points: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'groupId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'joinGroup'): TypedContractMethod<
      [identityCommitment: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'semaphore'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sendFeedback'): TypedContractMethod<
      [merkleTreeDepth: BigNumberish, merkleTreeRoot: BigNumberish, nullifier: BigNumberish, feedback: BigNumberish, points: BigNumberish[], ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }