/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CicadaVote', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CicadaVote__factory>
getContractFactory(name: 'Feedback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Feedback__factory>
getContractFactory(name: 'LibPrime', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibPrime__factory>
getContractFactory(name: 'LibUint1024', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LibUint1024__factory>
getContractFactory(name: 'IHederaTokenService', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHederaTokenService__factory>
getContractFactory(name: 'IPoSQLVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPoSQLVerifier__factory>
getContractFactory(name: 'MintController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MintController__factory>
getContractFactory(name: 'MyHTSToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyHTSToken__factory>
getContractFactory(name: 'Semaphore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Semaphore__factory>
getContractFactory(name: 'SemaphoreCicada', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SemaphoreCicada__factory>
getContractFactory(name: 'TokenManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenManager__factory>
getContractFactory(name: 'SemaphoreGroups', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SemaphoreGroups__factory>
getContractFactory(name: 'SemaphoreVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SemaphoreVerifier__factory>
getContractFactory(name: 'SemaphoreVerifierKeyPts', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SemaphoreVerifierKeyPts__factory>
getContractFactory(name: 'ISemaphore', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISemaphore__factory>
getContractFactory(name: 'ISemaphoreGroups', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISemaphoreGroups__factory>
getContractFactory(name: 'ISemaphoreVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISemaphoreVerifier__factory>
getContractFactory(name: 'PoseidonT3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PoseidonT3__factory>

  getContractAt(name: 'CicadaVote', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CicadaVote>
getContractAt(name: 'Feedback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Feedback>
getContractAt(name: 'LibPrime', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibPrime>
getContractAt(name: 'LibUint1024', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LibUint1024>
getContractAt(name: 'IHederaTokenService', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHederaTokenService>
getContractAt(name: 'IPoSQLVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPoSQLVerifier>
getContractAt(name: 'MintController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MintController>
getContractAt(name: 'MyHTSToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyHTSToken>
getContractAt(name: 'Semaphore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Semaphore>
getContractAt(name: 'SemaphoreCicada', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SemaphoreCicada>
getContractAt(name: 'TokenManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenManager>
getContractAt(name: 'SemaphoreGroups', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SemaphoreGroups>
getContractAt(name: 'SemaphoreVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SemaphoreVerifier>
getContractAt(name: 'SemaphoreVerifierKeyPts', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SemaphoreVerifierKeyPts>
getContractAt(name: 'ISemaphore', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISemaphore>
getContractAt(name: 'ISemaphoreGroups', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISemaphoreGroups>
getContractAt(name: 'ISemaphoreVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISemaphoreVerifier>
getContractAt(name: 'PoseidonT3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PoseidonT3>

  deployContract(name: 'CicadaVote', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CicadaVote>
deployContract(name: 'Feedback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Feedback>
deployContract(name: 'LibPrime', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibPrime>
deployContract(name: 'LibUint1024', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibUint1024>
deployContract(name: 'IHederaTokenService', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenService>
deployContract(name: 'IPoSQLVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPoSQLVerifier>
deployContract(name: 'MintController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MintController>
deployContract(name: 'MyHTSToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyHTSToken>
deployContract(name: 'Semaphore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Semaphore>
deployContract(name: 'SemaphoreCicada', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreCicada>
deployContract(name: 'TokenManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenManager>
deployContract(name: 'SemaphoreGroups', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreGroups>
deployContract(name: 'SemaphoreVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreVerifier>
deployContract(name: 'SemaphoreVerifierKeyPts', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreVerifierKeyPts>
deployContract(name: 'ISemaphore', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphore>
deployContract(name: 'ISemaphoreGroups', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphoreGroups>
deployContract(name: 'ISemaphoreVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphoreVerifier>
deployContract(name: 'PoseidonT3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoseidonT3>

  deployContract(name: 'CicadaVote', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CicadaVote>
deployContract(name: 'Feedback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Feedback>
deployContract(name: 'LibPrime', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibPrime>
deployContract(name: 'LibUint1024', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LibUint1024>
deployContract(name: 'IHederaTokenService', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenService>
deployContract(name: 'IPoSQLVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPoSQLVerifier>
deployContract(name: 'MintController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MintController>
deployContract(name: 'MyHTSToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyHTSToken>
deployContract(name: 'Semaphore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Semaphore>
deployContract(name: 'SemaphoreCicada', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreCicada>
deployContract(name: 'TokenManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenManager>
deployContract(name: 'SemaphoreGroups', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreGroups>
deployContract(name: 'SemaphoreVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreVerifier>
deployContract(name: 'SemaphoreVerifierKeyPts', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SemaphoreVerifierKeyPts>
deployContract(name: 'ISemaphore', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphore>
deployContract(name: 'ISemaphoreGroups', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphoreGroups>
deployContract(name: 'ISemaphoreVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISemaphoreVerifier>
deployContract(name: 'PoseidonT3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PoseidonT3>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  