/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISemaphore } from './ISemaphore.js';
export type { ISemaphoreGroups } from './ISemaphoreGroups.js';
export type { ISemaphoreVerifier } from './ISemaphoreVerifier.js';