/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IHederaTokenServiceInterface extends Interface {
    getFunction(nameOrSignature: "mintToken"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'mintToken', values: [AddressLike, BigNumberish, BytesLike[]]): string;

    decodeFunctionResult(functionFragment: 'mintToken', data: BytesLike): Result;
  }

  

  export interface IHederaTokenService extends BaseContract {
    
    connect(runner?: ContractRunner | null): IHederaTokenService;
    waitForDeployment(): Promise<this>;

    interface: IHederaTokenServiceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    mintToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, metadata: BytesLike[], ],
      [[bigint, bigint, bigint[]] & {responseCode: bigint, newTotalSupply: bigint, serialNumbers: bigint[] }],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'mintToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, metadata: BytesLike[], ],
      [[bigint, bigint, bigint[]] & {responseCode: bigint, newTotalSupply: bigint, serialNumbers: bigint[] }],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }