/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MintControllerInterface extends Interface {
    getFunction(nameOrSignature: "lastPegUpdate" | "mintWithProof" | "timelock" | "token" | "updatePeg" | "usedProofs" | "verifier"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'lastPegUpdate', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintWithProof', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'timelock', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePeg', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usedProofs', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'lastPegUpdate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintWithProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'timelock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePeg', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedProofs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
  }

  

  export interface MintController extends BaseContract {
    
    connect(runner?: ContractRunner | null): MintController;
    waitForDeployment(): Promise<this>;

    interface: MintControllerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    lastPegUpdate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintWithProof: TypedContractMethod<
      [query: BytesLike, proof: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    timelock: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updatePeg: TypedContractMethod<
      [newPeg: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usedProofs: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'lastPegUpdate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintWithProof'): TypedContractMethod<
      [query: BytesLike, proof: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'timelock'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updatePeg'): TypedContractMethod<
      [newPeg: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usedProofs'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }