/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { SemaphoreVerifierKeyPts, SemaphoreVerifierKeyPtsInterface } from "../../base/SemaphoreVerifierKeyPts.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "actual",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expected",
        "type": "uint256"
      }
    ],
    "name": "Semaphore__VKPtBytesMaxDepthInvariantViolated",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122052358682dbfcc6e6f1ded8398055e6de024848f0b9e241903464fe576e8d1a3964736f6c634300081c0033";

  
      type SemaphoreVerifierKeyPtsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SemaphoreVerifierKeyPtsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SemaphoreVerifierKeyPts__factory extends ContractFactory {
    
      constructor(...args: SemaphoreVerifierKeyPtsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SemaphoreVerifierKeyPts & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SemaphoreVerifierKeyPts__factory {
      return super.connect(runner) as SemaphoreVerifierKeyPts__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SemaphoreVerifierKeyPtsInterface {
      return new Interface(_abi) as SemaphoreVerifierKeyPtsInterface;
    }
    
    override attach(address: string | Addressable): SemaphoreVerifierKeyPts {
      return super.attach(address) as SemaphoreVerifierKeyPts;
    }
  static connect(address: string, runner?: ContractRunner | null): SemaphoreVerifierKeyPts {
      return new Contract(address, _abi, runner) as unknown as SemaphoreVerifierKeyPts;
    }
  }

  
  