/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { CicadaVote, CicadaVoteInterface } from "../../voting/CicadaVote.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InvalidBallot",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidProofOfExponentiation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPuzzleSolution",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidStartTime",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ParametersHashMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VoteAlreadyFinalized",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VoteHasNotEnded",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VoteIsNotOngoing",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "voteId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "description",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "startTime",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "endTime",
        "type": "uint64"
      },
      {
        "components": [
          {
            "internalType": "uint256[4]",
            "name": "N",
            "type": "uint256[4]"
          },
          {
            "internalType": "uint256",
            "name": "T",
            "type": "uint256"
          },
          {
            "internalType": "uint256[4]",
            "name": "g",
            "type": "uint256[4]"
          },
          {
            "internalType": "uint256[4]",
            "name": "h",
            "type": "uint256[4]"
          },
          {
            "internalType": "uint256[4]",
            "name": "y",
            "type": "uint256[4]"
          },
          {
            "internalType": "uint256[4]",
            "name": "yInv",
            "type": "uint256[4]"
          }
        ],
        "indexed": false,
        "internalType": "struct CicadaVote.PublicParameters",
        "name": "pp",
        "type": "tuple"
      }
    ],
    "name": "VoteCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "voteId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "numYesVotes",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "numNoVotes",
        "type": "uint64"
      }
    ],
    "name": "VoteFinalized",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "nextVoteId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "votes",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "parametersHash",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "uint256[4]",
            "name": "u",
            "type": "uint256[4]"
          },
          {
            "internalType": "uint256[4]",
            "name": "v",
            "type": "uint256[4]"
          }
        ],
        "internalType": "struct CicadaVote.Puzzle",
        "name": "tally",
        "type": "tuple"
      },
      {
        "internalType": "uint64",
        "name": "numVotes",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "startTime",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "endTime",
        "type": "uint64"
      },
      {
        "internalType": "bool",
        "name": "isFinalized",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class CicadaVote__factory {
    static readonly abi = _abi;
    static createInterface(): CicadaVoteInterface {
      return new Interface(_abi) as CicadaVoteInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): CicadaVote {
      return new Contract(address, _abi, runner) as unknown as CicadaVote;
    }
  }
  