/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { LibPrime, LibPrimeInterface } from "../LibPrime.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "input",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "prime",
        "type": "uint256"
      }
    ],
    "name": "InvalidHashToPrime",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212207df60b8f9c8fc053bc7bb58cdc8d637a27765e3dd612016ff7030792a361b50864736f6c634300081c0033";

  
      type LibPrimeConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibPrimeConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibPrime__factory extends ContractFactory {
    
      constructor(...args: LibPrimeConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibPrime & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibPrime__factory {
      return super.connect(runner) as LibPrime__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibPrimeInterface {
      return new Interface(_abi) as LibPrimeInterface;
    }
    
    override attach(address: string | Addressable): LibPrime {
      return super.attach(address) as LibPrime;
    }
  static connect(address: string, runner?: ContractRunner | null): LibPrime {
      return new Contract(address, _abi, runner) as unknown as LibPrime;
    }
  }

  
  