/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { LibUint1024, LibUint1024Interface } from "../../lib/LibUint1024.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[4]",
        "name": "a",
        "type": "uint256[4]"
      },
      {
        "internalType": "uint256[4]",
        "name": "b",
        "type": "uint256[4]"
      }
    ],
    "name": "Overflow",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256[4]",
        "name": "a",
        "type": "uint256[4]"
      },
      {
        "internalType": "uint256[4]",
        "name": "b",
        "type": "uint256[4]"
      }
    ],
    "name": "Underflow",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122057978a35d7fc82091f3f2ced0568cf5b50ab27ce2afe78b17a60b12a16d9942964736f6c634300081c0033";

  
      type LibUint1024ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: LibUint1024ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class LibUint1024__factory extends ContractFactory {
    
      constructor(...args: LibUint1024ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<LibUint1024 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): LibUint1024__factory {
      return super.connect(runner) as LibUint1024__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): LibUint1024Interface {
      return new Interface(_abi) as LibUint1024Interface;
    }
    
    override attach(address: string | Addressable): LibUint1024 {
      return super.attach(address) as LibUint1024;
    }
  static connect(address: string, runner?: ContractRunner | null): LibUint1024 {
      return new Contract(address, _abi, runner) as unknown as LibUint1024;
    }
  }

  
  